### ISSUE TITLE
XML Schema error in test

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#1041]
```
  1) ItemsHelper schema_validate should validate a document
     Failure/Error: @xsd ||= Nokogiri::XML::Schema(File.read(File.expand_path(File.dirname(__FILE__) + '/xml/mods-3-6.xsd')))
     Nokogiri::XML::SyntaxError:
       1508:0: ERROR: attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}lang' does not resolve to a(n) attribute declaration.
     # ./app/helpers/items_helper.rb:9:in `schema_validate'
     # ./spec/helpers/items_helper_spec.rb:47:in `block (3 levels) in <top (required)>'
```

**Comment by jcoyne** [comment]
This was caused by the LoC turning off all their machines this weekend for maintenance.
