### ISSUE TITLE
APO controller tests break isolation, require VPN or TIMEOUT

### ISSUE THREAD

**Issue by atz** [sul-dlss/argo#13]
Two tests in the apo controller spec TIMEOUT unless on Stanford network or VPN, because they attempt to contact unknown remote server in the auto-population of workflow-related objects.  

This would be fine for optional tests but should be stubbed out for mainline tests.

Lines:
```
 rspec ./spec/controllers/apo_controller_spec.rb:22 # ApoController create should hit the registration service to register an apo and a collection
 rspec ./spec/controllers/apo_controller_spec.rb:34 # ApoController create should set apo workflows to priority 70
```

Example error:
```
  1) ApoController create should hit the registration service to register an apo and a collection
     Failure/Error: post 'register', example
     Errno::ETIMEDOUT:
       Operation timed out - connect(2)
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rest-client-1.6.8/lib/restclient/request.rb:206:in `transmit'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rest-client-1.6.8/lib/restclient/request.rb:68:in `execute'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rest-client-1.6.8/lib/restclient/request.rb:35:in `execute'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rest-client-1.6.8/lib/restclient/resource.rb:51:in `get'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/dor-workflow-service-1.7.2/lib/dor/services/workflow_service.rb:98:in `get_workflow_xml'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/dor-services-4.14.1/lib/dor/datastreams/workflow_ds.rb:56:in `content'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/dor-services-4.14.1/lib/dor/datastreams/workflow_ds.rb:51:in `ng_xml'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/om-1.8.0/lib/om/xml/document.rb:106:in `find_by_xpath'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/om-1.8.0/lib/om/xml/dynamic_node.rb:104:in `nodeset'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/dor-services-4.14.1/lib/dor/datastreams/workflow_ds.rb:70:in `workflows'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/dor-services-4.14.1/lib/dor/datastreams/workflow_ds.rb:98:in `to_solr'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/active-fedora-5.7.1/lib/active_fedora/base.rb:314:in `block in to_solr'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/active-fedora-5.7.1/lib/active_fedora/base.rb:313:in `each_value'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/active-fedora-5.7.1/lib/active_fedora/base.rb:313:in `to_solr'
     # ./config/initializers/indexing.rb:9:in `to_solr'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/dor-services-4.14.1/lib/dor/models/editable.rb:11:in `to_solr'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/dor-services-4.14.1/lib/dor/models/describable.rb:155:in `to_solr'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/dor-services-4.14.1/lib/dor/models/processable.rb:153:in `to_solr'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/solrizer-fedora-2.3.1/lib/solrizer/fedora/indexer.rb:154:in `create_document'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/solrizer-fedora-2.3.1/lib/solrizer/fedora/indexer.rb:177:in `index'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/solrizer-fedora-2.3.1/lib/solrizer/fedora/solrizer.rb:66:in `solrize'
     # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/active-fedora-5.7.1/lib/active_fedora/persistence.rb:87:in `update_index'
     # ./app/controllers/apo_controller.rb:81:in `register'
...
```
It is possible the bug is in dor-services or a lower level dependency.

**Comment by atz** [comment]
@wmene, @jmartin-sul : this fixes a longstanding gripe with APO tests working their way off-box.  The pattern may be useful for other apps/gems.
