### ISSUE TITLE
ReportsController tests are fragile

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#1611]
The tests depend on a certain condition in solr that they don't ensure before running.

```

  1) ReportController#pids returns json
     Failure/Error: expect(pids.first).to eq('br481xz7820')

       expected: "br481xz7820"
            got: "1231231"

       (compared using ==)
     # ./spec/controllers/report_controller_spec.rb:45:in `block (3 levels) in <top (required)>'

  2) ReportController download downloads valid CSV data
     Failure/Error: expect(data[1].first).to eq('br481xz7820') # first data row starts with pid

       expected: "br481xz7820"
            got: "1231231"

       (compared using ==)
     # ./spec/controllers/report_controller_spec.rb:96:in `block (3 levels) in <top (required)>'

  3) ReportController download downloads valid CSV data for specific fields
     Failure/Error: expect(data[1].first).to eq('br481xz7820') # first data row starts with pid

       expected: "br481xz7820"
            got: "1231231"

       (compared using ==)
     # ./spec/controllers/report_controller_spec.rb:104:in `block (3 levels) in <top (required)>'
```

**Comment by jcoyne** [comment]
These tests have been improved/eliminated.
