### ISSUE TITLE
Look into flappy item_registration_spec on main

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#2512]
```
1) Item registration page invokes item registration method with the expected values and relays errors properly
     Failure/Error:
       expect(registration_params).to include(
         'admin_policy' => ur_apo_id,
         'workflow_id' => 'goobiWF',
         'label' => 'object title',
         'tag' => ['Process : Content Type : Book (ltr)', 'tag : test', "Registered By : #{user.sunetid}"],
         'rights' => 'default',
         'collection' => '',
         'source_id' => 'source:id1'
       )
     
       expected {"action" => "create", "admin_policy" => "druid:hv992ry2431", "collection" => "", "controller" => "dor/object...s : Content Type : Book (ltr)", "tag : test", "Registered By : person93"], "workflow_id" => "goobiWF"} to include {"rights" => "default"}
       Diff:
       
       
       @@ -1,7 +1,11 @@
       +"action" => "create",
        "admin_policy" => "druid:hv992ry2431",
        "collection" => "",
       +"controller" => "dor/objects",
        "label" => "object title",
       -"rights" => "default",
       +"other_id" => "label:",
       +"project" => "",
       +"rights" => "world",
        "source_id" => "source:id1",
        "tag" => ["Process : Content Type : Book (ltr)", "tag : test", "Registered By : person93"],
        "workflow_id" => "goobiWF",
       
     # ./spec/features/item_registration_spec.rb:84:in `block (2 levels) in <top (required)>'
     # ./spec/support/feature_errors.rb:24:in `block (3 levels) in <top (required)>'
     # ./spec/support/feature_errors.rb:13:in `respond_without_detailed_exceptions'
     # ./spec/support/feature_errors.rb:23:in `block (2 levels) in <top (required)>'

Failed examples:

rspec ./spec/features/item_registration_spec.rb:39 # Item registration page invokes item registration method with the expected values and relays errors properly
```

**Comment by peetucket** [comment]
Can't reproduce locally at the moment :(

**Comment by jcoyne** [comment]
I think we fixed this one.
