### ISSUE TITLE
Items/file template makes failure-prone SFTP calls 

### ISSUE THREAD

**Issue by atz** [sul-dlss/argo#272]
Resulting in errors like:
```
App 16907 stderr: [ 2015-11-24 14:12:39.8255 17013/0x000000033a9438(Worker 1) utils.rb:85 ]: *** Exception ActionView::Template::Error in Rack application object (process 17013, thread 0x0000
App 16907 stderr:       from argo/shared/bundle/ruby/2.2.0/gems/net-ssh-2.6.8/lib/net/ssh.rb:207:in `start'
App 16907 stderr:       from argo/shared/bundle/ruby/2.2.0/gems/net-sftp-2.1.2/lib/net/sftp.rb:31:in `start'
App 16907 stderr:       from argo/shared/bundle/ruby/2.2.0/bundler/gems/dor-services-d96fb43e0854/lib/dor/models/contentable.rb:128:in `list_files'
App 16907 stderr:       from argo/releases/20151124212840/app/views/items/file.html.erb:3:in `_app_views_items_file_html_erb___4512794503005862502_69852560'
App 16907 stderr:       from argo/shared/bundle/ruby/2.2.0/gems/actionview-4.2.4/lib/action_view/template.rb:145:in `block in render'
App 16907 stderr:       from argo/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
...
```

Perhaps the template should be passed these values rather than invoking list_files directly?  Pretty sure that templates should not be making remote requests on their own.  

Certainly `dor-services` also should be more alert to the fact that the connection may fail.

**Comment by atz** [comment]
Error line is:
https://github.com/sul-dlss/argo/blob/develop/app/views/items/file.html.erb#L3

**Comment by drh-stanford** [comment]
I believe I've addressed this issue in PR https://github.com/sul-dlss/argo/pull/497. The `list_files` method is now called/rescued from inside the controller and tested like that.
