### ISSUE TITLE
The purge bulk action fails when an item does not have a valid cocina representation

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2770]
**Describe the bug**
The purge bulk action hits errors when running on objects without valid cocina representations. The error shows up in the log as

```
2021-06-29 06:02:16 UTC PurgeJob: Unexpected error for druid:bp438sq4203 (bulk_action.id=15298): Unprocessable Entity: 422 ({"errors":[{"status":"422","title":"Unexpected Cocina::Mapper.build error","detail":"unable to resolve a sourceId for druid:bp438sq4203","meta":{"backtrace":["/opt/app/dor_services/dor_services/releases/20210623170046/app/services/cocina/from_fedora/identification.rb:37:in `source_id'","/opt/app/dor_services/dor_services/releases/20210623170046/app/services/cocina/from_fedora/identification.rb:20:in `props'","/opt/app/dor_services/dor_services/releases/20210623170046/app/services/cocina/from_fedora/identification.rb:11:in `props'","/opt/app/dor_services/dor_services/releases/20210623170046/app/services/cocina/from_fedora/dro.rb:73:in `block in props'","/opt/app/dor_services/dor_services/releases/20210623170046/app/services/cocina/from_fedora/dro.rb:65:in `tap'","/opt/app/dor_services/dor_services/releases/20210623170046/app/services/cocina/from_fedora/dro.rb:65:in `props'","/opt/app/dor_services/dor_services/releases/20210623170046/app/services/cocina/from_fedora/dro.rb:11:in `props'","/opt/app/dor_services/dor_services/releases/20210623170046/app/services/cocina/mapper.rb:42:in `build'","/opt/app/dor_services/dor_services/releases/20210623170046/app/services/cocina/mapper.rb:28:in `build'","/opt/app/dor_services/dor_services/releases/20210623170046/app/controllers/objects_controller.rb:64:in `show'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/abstract_controller/base.rb:194:in `process_action'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_controller/metal/rendering.rb:30:in `process_action'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/abstract_controller/callbacks.rb:42:in `block in process_action'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:132:in `run_callbacks'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/abstract_controller/callbacks.rb:41:in `process_action'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_controller/metal/rescue.rb:22:in `process_action'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `block in instrument'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/notifications/instrumenter.rb:23:in `instrument'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `instrument'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_controller/metal/instrumentation.rb:32:in `process_action'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/railties/controller_runtime.rb:24:in `process_action'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/abstract_controller/base.rb:134:in `process'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionview-5.2.6/lib/action_view/rendering.rb:32:in `process'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_controller/metal.rb:191:in `dispatch'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_controller/metal.rb:252:in `dispatch'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/routing/route_set.rb:34:in `serve'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:52:in `block in serve'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:35:in `each'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:35:in `serve'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/routing/route_set.rb:840:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/committee-4.4.0/lib/committee/middleware/request_validation.rb:31:in `handle'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/committee-4.4.0/lib/committee/middleware/base.rb:24:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:98:in `run_callbacks'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/callbacks.rb:26:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/rack/logger.rb:26:in `block in call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `block in tagged'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:28:in `tagged'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `tagged'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/rack/logger.rb:26:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/request_id.rb:27:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/executor.rb:14:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/honeybadger-4.8.0/lib/honeybadger/rack/error_notifier.rb:33:in `block in call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/honeybadger-4.8.0/lib/honeybadger/agent.rb:426:in `with_rack_env'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/honeybadger-4.8.0/lib/honeybadger/rack/error_notifier.rb:30:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/honeybadger-4.8.0/lib/honeybadger/rack/user_feedback.rb:31:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/honeybadger-4.8.0/lib/honeybadger/rack/user_informer.rb:21:in `call'","/opt/app/dor_services/dor_services/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/engine.rb:524:in `call'","/usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'","/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'","/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'","/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'","/usr/share/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'"]}}]})
```

**User Impact**
This makes it impossible to clean up invalid items that should be purged, like the ETD parts objects. The purge action in Argo includes related clean up steps like clearing up solr. Items could be purged from Fedora but they might leave traces behind in other systems.

**To Reproduce**
1. Go to a part object like bb129rz2285
2. Try to purge it from a bulk action
3. See the error in the log.

**Expected behavior**
The purge bulk action should work on druids that have not been accessioned. Note that the blue button purge action does work on druids in the same state but this is not a practical approach to cleaning up the 10,000+ ETD parts objects.

**Additional context**
There will be about 22,000 HB errors related to this by the end of the night. I was trying to purge the ETD parts during a quiet time for the system. I tried to cancel the job but it's still running. Update: this topped out at 8K errors, reported as missing title and missing source id.

**Comment by jcoyne** [comment]
I believe the problem is that we need to load the cocina representation to see if you are authorized to purge the item.  If we can't load the item, then we can't check if you have the authorization to purge it.

**Comment by andrewjbtw** [comment]
Maybe I should just make these items valid cocina by adding filler datastreams.

**Comment by jcoyne** [comment]
Either that or we can purge them by using the console and skipping the authorization piece.  Perhaps attach a list of PIDs to purge.

**Comment by andrewjbtw** [comment]
I'm going to close this because we should keep the authorization requirement on the bulk action rather than allow a blanket admin permission to purge. At some point we will have only valid Cocina objects.

The purge blue button on the show page must work because we allow administrators to view druids in Argo even if the Cocina isn't valid. I think we want to keep that too for single druids so that we can continue to edit them, but at some point we'll have valid cocina there too and not need the override.

If I go the purge-via-console route for these druids, I'll open that in its own ticket.
