### ISSUE TITLE
Unable to display druid:bb004bn8654

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#289]
https://argo-stage.stanford.edu/catalog/druid:bb004bn8654

gets "Incomplete response received from application"

for reasons unknown. If caused by bad data, we want the display to be robust enough to recover/ignore, showing druids in place of missing references for instance.

**Comment by LynnMcRae** [comment]
More examples ... they all come from a facet search on Collection=Hydrus or an attempt to show that collection record.  
https://argo-stage.stanford.edu/catalog/druid:bb020ng8351
https://argo-stage.stanford.edu/catalog/druid:gb045hv3517

**Comment by darrenleeweber** [comment]
Displays OK on prod at https://argo.stanford.edu/catalog/druid:bb004bn8654

**Comment by darrenleeweber** [comment]
I wonder if this has something to do with the REVS image.  Fedora on my laptop complains about `Object not found in low-level storage: druid:bb004bn8654` when the request hits
http://localhost:8983/fedora/objects/druid:bb004bn8654?format=xml
This is after adding the FOXML to the `fedora_conf/data/bb004bn8654.xml` and running the rake loaders for test and development.  The fedora logs contain a more details trace but it doesn't really help to identify whether it's a failure to find the FOXML or the image, i.e.
```
WARN 2015-12-09 10:57:42.046 [qtp152005629-14 - /fedora/objects/druid:bb004bn8654?format=xml] (BaseRestResource) Resource not found: Object not found in low-level storage: druid:bb004bn8654; unable to fulfill REST API request
org.fcrepo.server.errors.ObjectNotInLowlevelStorageException: Object not found in low-level storage: druid:bb004bn8654
	at org.fcrepo.server.storage.lowlevel.akubra.AkubraLowlevelStorage.retrieve(AkubraLowlevelStorage.java:423) ~[fcrepo-server-3.7.1.jar:na]
	at org.fcrepo.server.storage.lowlevel.akubra.AkubraLowlevelStorage.retrieveObject(AkubraLowlevelStorage.java:180) ~[fcrepo-server-3.7.1.jar:na]
	at org.fcrepo.server.storage.lowlevel.akubra.AkubraLowlevelStorageModule.retrieveObject(AkubraLowlevelStorageModule.java:83) ~[fcrepo-server-3.7.1.jar:na]
	at org.fcrepo.server.storage.DefaultDOManager.getReader(DefaultDOManager.java:709) ~[fcrepo-server-3.7.1.jar:na]
	at org.fcrepo.server.access.DefaultAccess.getObjectProfile(DefaultAccess.java:620) ~[fcrepo-server-3.7.1.jar:na]
	at org.fcrepo.server.rest.FedoraObjectsResource.getObjectProfile(FedoraObjectsResource.java:351) ~[fcrepo-server-3.7.1.jar:na]
```

**Comment by darrenleeweber** [comment]
The argo-prod throws back an ActiveFedora exception when it hits a missing DRUID, e.g. see
https://argo.stanford.edu/catalog/druid:qv648vd4395

Maybe there was another ticket to hide these exceptions and present the simpler message about 'incomplete response ...'?

**Comment by darrenleeweber** [comment]
This could be an issue with loading FOXML into stage, because this DRUID contains a lot of 'INTERNAL_ID' for versions of data streams.

**Comment by darrenleeweber** [comment]
The 'incomplete response ...' string is nowhere in the argo app, i.e.  `ack-grep 'Incomplete response received from application'` at the root of the code repo returns nothing.  This response may be controlled by a dependent gem?

**Comment by darrenleeweber** [comment]
Located this object in fedora-stage at
 - https://sul-dor-test/fedora/objects/druid:Abb004bn8654

**Comment by darrenleeweber** [comment]
There is an indexed document in Solr, which was found at
  - https://sul-solr.stanford.edu/solr/argo_stage_shard1_replica2/select?q=druid%3Abb004bn8654&wt=json&indent=true

**Comment by darrenleeweber** [comment]
The argo stage logs for this query indicate a problem in the view, i.e.
```
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Started GET "/catalog/druid:bb004bn8654" for 171.67.138.27 at 2015-12-09 14:34:17 -0800
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Processing by CatalogController#show as HTML
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863]   Parameters: {"id"=>"druid:bb004bn8654"}
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863]   User Load (0.7ms)  SELECT  `users`.* FROM `users` WHERE `users`.`sunetid` = 'dlweber' LIMIT 1
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863]   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`sunetid` = 'dlweber' LIMIT 1  [["sunetid", "dlweber"]]
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream list for druid:bb004bn8654 (42.4ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream profile druid:bb004bn8654/RELS-EXT (40.8ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream content druid:bb004bn8654/RELS-EXT (43.0ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream profile druid:bb004bn8654/identityMetadata (43.4ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream content druid:bb004bn8654/identityMetadata (39.3ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream profile druid:bb004bn8654/workflows (39.4ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream profile druid:bb004bn8654/contentMetadata (38.3ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream profile druid:bb004bn8654/rightsMetadata (42.1ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream content druid:bb004bn8654/rightsMetadata (39.3ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream profile druid:bb004bn8654/descMetadata (38.9ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream profile druid:bb004bn8654/embargoMetadata (40.4ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream content druid:bb004bn8654/embargoMetadata (42.2ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream profile druid:bb004bn8654/provenanceMetadata (39.5ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream content druid:bb004bn8654/provenanceMetadata (48.7ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream profile druid:bb004bn8654/technicalMetadata (44.6ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream profile druid:bb004bn8654/versionMetadata (39.4ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream content druid:bb004bn8654/versionMetadata (46.6ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream profile druid:bb004bn8654/versionMetadata (53.4ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream profile druid:bb004bn8654/workflows (34.8ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream list for druid:qv648vd4392 (51.6ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream profile druid:qv648vd4392/RELS-EXT (45.5ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream content druid:qv648vd4392/RELS-EXT (39.6ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Loaded datastream profile druid:qv648vd4392/workflows (39.1ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Solr query: {:qt=>"/document", :id=>"druid:bb004bn8654"}
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Solr fetch (116.4ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863]   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`sunetid` = 'dlweber' LIMIT 1  [["sunetid", "dlweber"]]
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863]   CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`sunetid` = 'dlweber' LIMIT 1  [["sunetid", "dlweber"]]
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863]   Rendered items/_button_link_list.html.erb (1.0ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863]   Rendered catalog/_show_external_links.html.erb (328.7ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863]   Rendered catalog/_show_embargo_sidebar.html.erb (0.1ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863]   Rendered catalog/_show_sidebar.html.erb (329.4ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863]   Rendered /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/blacklight-5.9.4/app/views/catalog/_constraints.html.erb (0.2ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863]   Rendered /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/blacklight-5.9.4/app/views/catalog/_previous_next_doc.html.erb (0.3ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Looking for document partial show_list_item
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Looking for document partial show_list_default
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Looking for document partial show_item
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Looking for document partial show_default
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863]   Rendered catalog/_show_field_list.html.erb (2.3ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863]   Rendered catalog/_show_field_list.html.erb (3.7ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863]   Rendered catalog/_show_field_list.html.erb (1.9ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863]   Rendered catalog/_show_sections/_default_identification.html.erb (9.4ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863]   Rendered catalog/_show_section.html.erb (10.0ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863]   Rendered catalog/show.html.erb within layouts/application (345.1ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] Completed 500 Internal Server Error in 1801ms (ActiveRecord: 0.8ms)
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] [failsafe_handler] 2015-12-09 14:34:20 -0800 - Original error: (ActionView::Template::Error) argument out of range
[2aebbe24-9a9b-4330-8fe0-84f269d2cd86] [2015-12-09 22:34:17.863] [failsafe_handler]   /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/time.rb:300:in `local'
  /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/time.rb:300:in `make_time'
  /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/time.rb:364:in `parse'
  /opt/app/lyberadmin/argo/releases/20151208015527/app/helpers/value_helper.rb:73:in `value_for_originInfo_date_created_tesim'
  /opt/app/lyberadmin/argo/releases/20151208015527/app/helpers/argo_helper.rb:47:in `render_document_show_field_value'
  /opt/app/lyberadmin/argo/releases/20151208015527/app/views/catalog/_show_field_list.html.erb:7:in `block in _app_views_catalog__show_field_list_html_erb___2207021347081859659_70073535100600'
  /opt/app/lyberadmin/argo/releases/20151208015527/app/views/catalog/_show_field_list.html.erb:2:in `each'
  /opt/app/lyberadmin/argo/releases/20151208015527/app/views/catalog/_show_field_list.html.erb:2:in `_app_views_catalog__show_field_list_html_erb___2207021347081859659_70073535100600'
  /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/actionview-4.2.4/lib/action_view/template.rb:145:in `block in render'
  /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
  /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
  /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/actionview-4.2.4/lib/action_view/template.rb:333:in `instrument'
  /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/actionview-4.2.4/lib/action_view/template.rb:143:in `render'
  /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/actionview-4.2.4/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
```

**Comment by atz** [comment]
So you should be able to find a bad date value in `value_for_originInfo_date_created_tesim`... which is not surprising since it is a text field holding an expected date value.... what could go wrong?

**Comment by darrenleeweber** [comment]
The view is failing to parse a datetime or date or time from
```
"originInfo_date_created_tesim":
[
    "1966"
],
"originInfo_0_date_created_tesim": 
[
    "1966"
],
```

**Comment by darrenleeweber** [comment]
Initial attempt to modify the value handler is in https://github.com/sul-dlss/argo/pull/336

**Comment by darrenleeweber** [comment]
Deployed the `issue289` branch of #336 to argo-stage and confirmed that it displays these:
  - https://argo-stage.stanford.edu/catalog/druid:bb004bn8654
  - https://argo-stage.stanford.edu/catalog/druid:bb020ng8351
  - https://argo-stage.stanford.edu/catalog/druid:gb045hv3517

The last 2 druids do not have any 'Created' fields in this display, so it's not clear why they did not display before because the fix in `issue289` only applies to that field.
