### ISSUE TITLE
Multiple bulk updates are not working

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2937]
**Describe the bug**
Multiple bulk updates are failing with the following error: "error : Unprocessable Entity".

I haven't checked each update but both the "set source id" and the "update tags" bulk updates are failing in the same way. I haven't found any honeybadger errors corresponding to this issue, just error message reported in browser.

Note that this issue is for the bulk updates page at https://argo.stanford.edu/report/bulk - not the bulk updates. The results of the job are reported at the bottom of the bottom of the browser window:

<img width="429" alt="Screen Shot 2022-01-04 at 9 43 27 PM" src="https://user-images.githubusercontent.com/8975583/148172495-d80325a2-6473-40a3-b5a6-dd8ab4ba0ae1.png">

**User Impact**
It's not possible to run these bulk updates. I'm not sure if all bulk updates are broken or just these two.

**To Reproduce**
Steps to reproduce the behavior for a bulk tag update
1. Go to https://argo-stage.stanford.edu/report/bulk?f%5Btag_ssim%5D%5B%5D=Foo+%3A+Bar
2. Click on the "Tags" button
3. Scroll down to see the text box that appears with the existing tags filled in
4. Change the tag from "Foo : Bar" to something else, like "Foo : Bah"
5. Click the "Update Tags" button
6. See the error appear below

You can also reproduce the same issue by trying to change a source id. Note that items need to be in an "Opened" state before changing source id.

**Expected behavior**
The bulk updates should go through the list of druids and update them accordingly, reporting back to the same browser window.

**Additional context**
We have an alternative method of changing tags that uses a CSV so that particular bulk update is not blocked. But the other updates can't be done other ways. This issue came up when I was helping someone change some source ids.

**Comment by jcoyne** [comment]
The problem is an invalid authenticity token:
```
F, [2022-01-05T06:10:15.197948 #26743] FATAL -- : [7d338499-136f-4b5d-90c1-362b35728653]
[7d338499-136f-4b5d-90c1-362b35728653] ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
[7d338499-136f-4b5d-90c1-362b35728653]
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'
[7d338499-136f-4b5d-90c1-362b35728653] devise (4.8.1) lib/devise/controllers/helpers.rb:255:in `handle_unverified_request'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_controller/metal/request_forgery_protection.rb:238:in `verify_authenticity_token'
[7d338499-136f-4b5d-90c1-362b35728653] activesupport (6.1.4.4) lib/active_support/callbacks.rb:427:in `block in make_lambda'
[7d338499-136f-4b5d-90c1-362b35728653] activesupport (6.1.4.4) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
[7d338499-136f-4b5d-90c1-362b35728653] activesupport (6.1.4.4) lib/active_support/callbacks.rb:199:in `block in halting'
[7d338499-136f-4b5d-90c1-362b35728653] activesupport (6.1.4.4) lib/active_support/callbacks.rb:512:in `block in invoke_before'
[7d338499-136f-4b5d-90c1-362b35728653] activesupport (6.1.4.4) lib/active_support/callbacks.rb:512:in `each'
[7d338499-136f-4b5d-90c1-362b35728653] activesupport (6.1.4.4) lib/active_support/callbacks.rb:512:in `invoke_before'
[7d338499-136f-4b5d-90c1-362b35728653] activesupport (6.1.4.4) lib/active_support/callbacks.rb:115:in `block in run_callbacks'
[7d338499-136f-4b5d-90c1-362b35728653] activesupport (6.1.4.4) lib/active_support/callbacks.rb:137:in `run_callbacks'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
[7d338499-136f-4b5d-90c1-362b35728653] activesupport (6.1.4.4) lib/active_support/notifications.rb:203:in `block in instrument'
[7d338499-136f-4b5d-90c1-362b35728653] activesupport (6.1.4.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[7d338499-136f-4b5d-90c1-362b35728653] activesupport (6.1.4.4) lib/active_support/notifications.rb:203:in `instrument'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
[7d338499-136f-4b5d-90c1-362b35728653] activerecord (6.1.4.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/abstract_controller/base.rb:165:in `process'
[7d338499-136f-4b5d-90c1-362b35728653] actionview (6.1.4.4) lib/action_view/rendering.rb:39:in `process'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_controller/metal.rb:190:in `dispatch'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_controller/metal.rb:254:in `dispatch'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_dispatch/routing/route_set.rb:33:in `serve'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_dispatch/journey/router.rb:32:in `each'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_dispatch/journey/router.rb:32:in `serve'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_dispatch/routing/route_set.rb:842:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/rack/browser_monitoring.rb:33:in `traced_call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
[7d338499-136f-4b5d-90c1-362b35728653] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
[7d338499-136f-4b5d-90c1-362b35728653] warden (1.2.9) lib/warden/manager.rb:34:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] rack (2.2.3) lib/rack/etag.rb:27:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] rack (2.2.3) lib/rack/head.rb:12:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
[7d338499-136f-4b5d-90c1-362b35728653] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_dispatch/middleware/cookies.rb:689:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[7d338499-136f-4b5d-90c1-362b35728653] activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] lograge (0.11.2) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
[7d338499-136f-4b5d-90c1-362b35728653] railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
[7d338499-136f-4b5d-90c1-362b35728653] activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
[7d338499-136f-4b5d-90c1-362b35728653] activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
[7d338499-136f-4b5d-90c1-362b35728653] activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
[7d338499-136f-4b5d-90c1-362b35728653] railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] rack (2.2.3) lib/rack/method_override.rb:24:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:113:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] honeybadger (4.9.0) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
[7d338499-136f-4b5d-90c1-362b35728653] honeybadger (4.9.0) lib/honeybadger/agent.rb:426:in `with_rack_env'
[7d338499-136f-4b5d-90c1-362b35728653] honeybadger (4.9.0) lib/honeybadger/rack/error_notifier.rb:30:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] honeybadger (4.9.0) lib/honeybadger/rack/user_feedback.rb:31:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] honeybadger (4.9.0) lib/honeybadger/rack/user_informer.rb:21:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] newrelic_rpm (8.2.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
[7d338499-136f-4b5d-90c1-362b35728653] /usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
[7d338499-136f-4b5d-90c1-362b35728653] /usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
[7d338499-136f-4b5d-90c1-362b35728653] /usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
[7d338499-136f-4b5d-90c1-362b35728653] /usr/share/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
[7d338499-136f-4b5d-90c1-362b35728653] /usr/share/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by jcoyne** [comment]
I think it's because this old jquery Ajax depends on rails-ujs without saying so:
https://github.com/sul-dlss/argo/blob/main/app/javascript/bulk.js#L235 . Other bulk actions send the token explicitly: https://github.com/sul-dlss/argo/blob/b760d1e43791902e03b4d256e103a097dd1fdd7f/app/javascript/bulk.js#L11
