### ISSUE TITLE
ci build fails on develop sporadically

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/argo#304]
The `develop` build is failing sporadically on Travis. See https://travis-ci.org/sul-dlss/argo/builds/95020769 for a failure example and https://travis-ci.org/sul-dlss/argo/builds/95022296 for a success example

The build errors are these:

```
  1) Date range form with no after date
     Failure/Error: find('#appliedParams')
     Capybara::ElementNotFound:
       Unable to find css "#appliedParams"
     # ./spec/features/date_range_form_spec.rb:45:in `block (2 levels) in <top (required)>'
  2) Date range form with no before date
     Failure/Error: find('#appliedParams')
     Capybara::ElementNotFound:
       Unable to find css "#appliedParams"
     # ./spec/features/date_range_form_spec.rb:60:in `block (2 levels) in <top (required)>'
```

I tried increasing the Capybara timeout but that hasn't worked on my laptop. It seems hung on the visit of the page.

**Comment by drh-stanford** [comment]
I turned on debugging for poltergeist and I get the following for the first failure:

```json
{"name":"visit","args":["http://127.0.0.1:49331/"]}
{"response":{"status":"success"}}
{"name":"find","args":["css","[data-target=\"#facet-object_modified_date\"]"]}
{"response":{"page_id":2,"ids":[0]}}
{"name":"visible","args":[2,0]}
{"response":true}
{"name":"click","args":[2,0]}
{"response":{"position":{"x":128,"y":749.5}}}
{"name":"find","args":["css","#facet-object_modified_date"]}
{"response":{"page_id":2,"ids":[1]}}
{"name":"visible","args":[2,1]}
{"response":true}
{"name":"find_within","args":[2,1,"xpath",".//*[self::input | self::textarea][not(./@type = 'submit' or ./@type = 'image' or ./@type = 'radio' or ./@type = 'checkbox' or ./@type = 'hidden' or ./@type = 'file')][(((./@id = 'object_modified_date_before_datepicker' or ./@name = 'object_modified_date_before_datepicker') or ./@placeholder = 'object_modified_date_before_datepicker') or ./@id = //label[normalize-space(string(.)) = 'object_modified_date_before_datepicker']/@for)] | .//label[normalize-space(string(.)) = 'object_modified_date_before_datepicker']//.//*[self::input | self::textarea][not(./@type = 'submit' or ./@type = 'image' or ./@type = 'radio' or ./@type = 'checkbox' or ./@type = 'hidden' or ./@type = 'file')]"]}
{"response":[2]}
{"name":"visible","args":[2,2]}
{"response":true}
{"name":"disabled","args":[2,2]}
{"response":false}
{"name":"tag_name","args":[2,2]}
{"response":"INPUT"}
{"name":"attribute","args":[2,2,"type"]}
{"response":"text"}
{"name":"set","args":[2,2,"12/06/2015"]}
{"response":true}
{"name":"find_within","args":[2,1,"css","#object_modified_date"]}
{"response":[3]}
{"name":"visible","args":[2,3]}
{"response":true}
{"name":"click","args":[2,3]}
{"response":{"position":{"x":61.5,"y":405}}}
{"name":"evaluate","args":["window.location.reload()"]}
{"response":null}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":2,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":2,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":2,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":2,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":2,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":2,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":2,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":2,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":2,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":2,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"find","args":["css","#appliedParams"]}
{"response":{"page_id":3,"ids":[]}}
{"name":"reset","args":[]}
{"response":true}
{"name":"find","args":["xpath","/html/body/*"]}
{"response":{"page_id":0,"ids":[]}}
  with no after date (FAILED - 1)
```

**Comment by mejackreed** [comment]
This is due to the way we are changing page location in JavaScript. Really what should be done is this date range functionality should be converted to be handled server side. Capybara/Poltergeist is not recognizing the page change when executed here:

https://github.com/sul-dlss/argo/blob/develop/app/assets/javascripts/modules/date_range_query.js#L45

**Comment by drh-stanford** [comment]
What do you recommend? Should we disable those tests for now? Or is there another way to implement the feature in the client-side JavaScript that would accommodate the testing framework?

**Comment by mejackreed** [comment]
I think for now, if the test fails on Travis, just rerun it. (not a long term solution, but short term fix). We have this problem in other applications as well. I think the thought process is better to have sporadic false  fails rather than not testing it. Next week, we can look at changing the code to handle this better.

**Comment by drh-stanford** [comment]
the builds are still failing despite #332

**Comment by drh-stanford** [comment]
travis has a `travis_retry` command that we could prepend to the bundle exec rake ci. see https://blog.travis-ci.com/2013-05-20-network-timeouts-build-retries/

**Comment by drh-stanford** [comment]
Another option is to try (no pun intended) out the `rspec-retry` gem. See #351 comments.

**Comment by mejackreed** [comment]
Let's keep an eye on things, but I think https://github.com/sul-dlss/argo/pull/353 might have solved our issues. https://github.com/sul-dlss/argo/pull/352#issue-121720520 for approach and metrics related to various fix tries.
