### ISSUE TITLE
when a user is in too many workgroups, they can't use Argo

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#321]
more specifically, when the user is in too many workgroups that are recognized by argo (i.e. listed in .htaccess), and those workgroups are passed to the solr query that does permission checks.  when the query string is too long, the solr request fails, and the page loads that use that perm check (e.g. the front page) error out.

the error the user sees is `Sorry, I don't understand your search.` (@rosy1280 has a screenshot).

the error solr returns is:
```
RSolr::Error::Http: RSolr::Error::Http - 414 Request-URI Too Long
Error: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>414 Request-URI Too Large</title>
</head><body>
<h1>Request-URI Too Large</h1>
<p>The requested URL's length exceeds the capacity
limit for this server.<br />
</p>
</body></html>
```

the stack trace is:
```
Backtrace: /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:284:in `adapt_response'
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:190:in `execute'
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:176:in `send_and_receive'
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rsolr-ext-1.0.3/lib/rsolr-ext/client.rb:21:in `find'
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/bundler/gems/dor-services-764ce0f299b9/lib/dor/services/search_service.rb:74:in `query'
/opt/app/lyberadmin/argo/releases/20151208015719/app/models/user.rb:64:in `permitted_apos'
(irb):59:in `irb_binding'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/irb/workspace.rb:86:in `eval'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/irb/workspace.rb:86:in `evaluate'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/irb/context.rb:379:in `evaluate'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/irb.rb:489:in `block (2 levels) in eval_input'
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:284:in `adapt_response'
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:190:in `execute'
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:176:in `send_and_receive'
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rsolr-ext-1.0.3/lib/rsolr-ext/client.rb:21:in `find'
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/bundler/gems/dor-services-764ce0f299b9/lib/dor/services/search_service.rb:74:in `query'
	from /opt/app/lyberadmin/argo/releases/20151208015719/app/models/user.rb:64:in `permitted_apos'
	from (irb):59
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'
```
(stack trace is from the current develop branch of argo, though this was initially discovered in argo 2.x on prod)

you can reproduce by:
```ruby
test_user = User::find_or_create_by_remoteuser 'test_user' #don't need a real user, we'll fake webauth groups anyway
test_user_groups = (0..30).map { |num| "workgroup:workgroup_#{num}" }
test_user.set_groups_to_impersonate test_user_groups
test_user.permitted_apos
```

the same error occurs in the UI if you impersonate and don't enter anything, or if you have a huge search that's way too long for solr in the same way as the above.

one fix, at least for the too-many-workgroups problem, would be to have the request to solr be a post.  i'm not sure how much control we have over this, as i'm not sure whether the request type can be set by dor-services, or if that's farther down the stack and harder to access.

**Comment by jmartin-sul** [comment]
we discovered this when joanna dyla ran into the issue whenever she tried to access argo (as did kim durante and a couple other people in their department).  in that case, it turns out that the query string was too long because the workgroups that the user was in resulted in too many applicable APOs being passed to a permissions check query, leading to the error for which this issue was filed.

**Comment by mejackreed** [comment]
See: https://github.com/projectblacklight/blacklight/issues/1324
