### ISSUE TITLE
Fix deployment

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/argo#3257]
Honeybadger step fails now:

```
01:09 honeybadger:deploy                                                                                                     [120/809]
      Notifying Honeybadger of deploy.                                                                                                
      01 RAILS_ENV=production bundle exec honeybadger deploy --environment qa --revision b3519f5a62400f92645ed60ed126617a524004da --r…
      01 /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.…
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'     
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/cocina-models-0.69.1/lib/cocina/rspec.rb:3:in `<main>'    
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kern
el_re…                                                                                                                                
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kern
el_re…                                                                                                                                
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'     
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const
_get'                                                                                                                                 
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:244:in `block (2 lev
els) …                                                                                                                                
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block
 in l…                                                                                                                                
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_
child'                                                                                                                                
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'  
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eag
er_lo…                                                                                                                                
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load' 
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'       
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_a
ll'                                                                                                                                   
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/application/finisher.rb:78:in `
block…
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `instanc
e_exe…
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `run'
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:61:in `block i
n run…
      01        from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
      01        from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_comp
onent'
      01        from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
      01        from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
      01        from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `each'
      01        from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `call'
      01        from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
      01        from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
      01        from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:60:in `run_ini
tiali…
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/application.rb:372:in `initiali
ze!'
      01        from /opt/app/lyberadmin/argo/releases/20220315191818/config/environment.rb:7:in `<top (required)>'
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/honeybadger-4.11.0/lib/honeybadger/cli/main.rb:178:in `req
uire'
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/honeybadger-4.11.0/lib/honeybadger/cli/main.rb:178:in `loa
d_rai…
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/honeybadger-4.11.0/lib/honeybadger/cli/main.rb:167:in `loa
d_rai…
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/honeybadger-4.11.0/lib/honeybadger/cli/main.rb:156:in `loa
d_env'
      01        from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/honeybadger-4.11.0/lib/honeybadger/cli/main.rb:142
```

**Comment by ndushay** [comment]
was this the wait-io problem?

**Comment by mjgiarlo** [comment]
Oof, thank you, @ndushay. This is indeed bogus/fixed. Closing!
