### ISSUE TITLE
solr_doc_params deprecated

### ISSUE THREAD

**Issue by atz** [sul-dlss/argo#35]
```
DEPRECATION WARNING: The #solr_doc_params method is deprecated. Instead, you should provide a custom SolrRepository implementation for the additional behavior you're offering. (called from show at /Users/atz/.rvm/gems/ruby-2.1.2/gems/blacklight-5.9.4/lib/blacklight/catalog.rb:51) (2 times); e.g.: 
    /Users/atz/.rvm/gems/ruby-2.1.2/gems/blacklight-5.9.4/lib/blacklight/catalog.rb:51:in `show'
    /Users/atz/repos/argo/app/controllers/catalog_controller.rb:188:in `show'
    /Users/atz/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
    /Users/atz/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in `process_action'
    /Users/atz/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
```

**Comment by atz** [comment]
Appears to be silenced by renaming to `default_solr_doc_params` (even though that is also marked as deprecated).  Annoying as hell.
