### ISSUE TITLE
Reduce Double DSA requests

### ISSUE THREAD

**Issue by edsu** [sul-dlss/argo#4076]
It appears that loading an object view, e.g. https://argo-stage.stanford.edu/view/druid:zs200kj4169 will trigger identical GET requests to dor-services-app. 

If you tail the DSA `log/production.log` while loading the Argo view you will see something like:

```
I, [2023-08-03T14:21:31.107123 #3844209]  INFO -- : [73fc3523-12f1-4f52-91c4-476f31ed8178] method=GET path=/v1/objects/druid:zs200kj4169 format=*/* controller=ObjectsController action=show status=200 duration=32.10 view=2.86 db=0.55
I, [2023-08-03T14:21:31.347867 #3844209]  INFO -- : [b4b0810f-9fe7-4475-aa32-c1ff3373e191] method=GET path=/v1/objects/druid:zs200kj4169 format=*/* controller=ObjectsController action=show status=200 duration=37.56 view=3.24 db=0.60
```

This is not a big deal most of the time, but for large objects it could potentially double the sluggishness?

**Comment by justinlittman** [comment]
Actually, looks like we may do it 5 times:
```
tail -f log/development.log | grep "Loading"
Loading cocina model for druid:fh251zq9084
Loading cocina model for druid:fh251zq9084
Loading cocina model for druid:fh251zq9084
Loading cocina model for druid:fh251zq9084
Loading cocina model for druid:fh251zq9084
```

**Comment by justinlittman** [comment]
Here's where the calls are coming from:
```
Loading cocina model for druid:fh251zq9084: /Users/jlittman/data/sdr/argo/app/controllers/catalog_controller.rb:232:in `show'
Loading cocina model for druid:fh251zq9084: /Users/jlittman/data/sdr/argo/app/controllers/workflow_service_controller.rb:24:in `load_cocina'
Loading cocina model for druid:fh251zq9084: /Users/jlittman/data/sdr/argo/app/controllers/workflow_service_controller.rb:24:in `load_cocina'
Loading cocina model for druid:fh251zq9084: /Users/jlittman/data/sdr/argo/app/controllers/workflow_service_controller.rb:24:in `load_cocina'
Loading cocina model for druid:fh251zq9084: /Users/jlittman/data/sdr/argo/app/controllers/structures_controller.rb:19:in `block (2 levels) in show'
```

**Comment by justinlittman** [comment]
Another option is to support a graphql style DSA API such that requests for cocina objects only request the parts of the object that are required (e.g., excluding structural).

**Comment by justinlittman** [comment]
Argo still makes multiple DSA requests (since parts of page is served in frames). However, since it now uses graphql endpoint for some of those requests, it is much faster.
