### ISSUE TITLE
Descriptive metadata download timeout

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/argo#714]
When using Bulk Actions to download descriptive metadata for large numbers of objects (more than 1000) it seems fairly common that some druids fail to load due to network problems. Investigate Fedora logs, and maybe retry the connection?

**Comment by tingulfsen** [comment]
Sample server download log output:

argo.bulk_metadata.bulk_log_bulk_action_success druid:bc211dq6680
argo.bulk_metadata.bulk_log_error_exception druid:bc235yp4467
getaddrinfo: Temporary failure in name resolution
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `open'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
...
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/dor-services-5.7.0/lib/dor-services.rb:45:in `find_all'
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/dor-services-5.7.0/lib/dor-services.rb:37:in `find'
/opt/app/lyberadmin/argo/releases/20160330231731/app/jobs/descmetadata_download_job.rb:25:in `block (3 levels) in perform'
/opt/app/lyberadmin/argo/releases/20160330231731/app/jobs/descmetadata_download_job.rb:23:in `each'

**Comment by tingulfsen** [comment]
More sample server download log output:

argo.bulk_metadata.bulk_log_bulk_action_success druid:cs543kw6620
argo.bulk_metadata.bulk_log_error_exception druid:cs555pj5449
Request Timeout
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:427:in `rescue in transmit'
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:350:in `transmit'
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
...
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/dor-services-5.7.0/lib/dor-services.rb:37:in `find'
/opt/app/lyberadmin/argo/releases/20160330231731/app/jobs/descmetadata_download_job.rb:25:in `block (3 levels) in perform'
/opt/app/lyberadmin/argo/releases/20160330231731/app/jobs/descmetadata_download_job.rb:23:in `each'
