### ISSUE TITLE
Fix pending unit tests for Argo

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#74]
Possibly an outdated tracking ticket. When last updated (Sept 22)  there were 9 outstanding unit tests John was working in.

**Comment by atz** [comment]
Candidates are:
```
 1) ApoController create should create an apo
     # Unimplemented
     Failure/Error: expect(@item).to receive(:add_roleplayer).exactly(4).times
       (#<Dor::AdminPolicyObject:0x007f83158bfb38>).add_roleplayer(*(any args))
           expected: 4 times with any arguments
           received: 0 times with any arguments
     # ./spec/controllers/apo_controller_spec.rb:25:in `block (3 levels) in <top (required)>'

  2) CatalogController bulk_jobs_index shows past bulk jobs for logged in users
     # implement as part of an integration test
     # ./spec/controllers/catalog_controller_spec.rb:64

  3) CatalogController valid_user? returns false when the given object is not an APO
     # test private methods as part of an integration test
     # ./spec/controllers/catalog_controller_spec.rb:71

  4) DorController dor indexing all of the solr fields argo depends on should be in a solr doc generated by to_solr
     # unimplemented: required fields not fully/uniquely identified
     # ./spec/controllers/dor_controller_spec.rb:75

  5) ReportController bulk should return a page with the expected elements
     # not sure why, but in this test the response comes back with no HTML, so the checks for expected content fail.  page works IRL, though.
     Failure/Error: expect(page).to include('Bulk update operations')
       expected #<Capybara::Session> to include "Bulk update operations", but it does not respond to `include?`
       Diff:
       @@ -1,2 +1,2 @@
       -["Bulk update operations"]
       +#<Capybara::Session>
       
     # ./spec/controllers/report_controller_spec.rb:33:in `block (3 levels) in <top (required)>'

  6) apo should register an apo
     # Did Argo ever register APOs?
     Failure/Error: visit url_for(:controller => :apo, :action => :register)
     Capybara::InfiniteRedirectError:
       redirected more than 5 times, check for infinite redirects.
     # /Users/atz/.rvm/gems/ruby-2.2.0/gems/capybara-2.5.0/lib/capybara/rack_test/browser.rb:40:in `process_and_follow_redirects'
     # /Users/atz/.rvm/gems/ruby-2.2.0/gems/capybara-2.5.0/lib/capybara/rack_test/browser.rb:21:in `visit'
     # /Users/atz/.rvm/gems/ruby-2.2.0/gems/capybara-2.5.0/lib/capybara/rack_test/driver.rb:42:in `visit'
     # /Users/atz/.rvm/gems/ruby-2.2.0/gems/capybara-2.5.0/lib/capybara/session.rb:232:in `visit'
     # /Users/atz/.rvm/gems/ruby-2.2.0/gems/capybara-2.5.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/integration/apo_spec.rb:14:in `block (2 levels) in <top (required)>'

  7) apo should edit an apo
     # Did Argo ever register APOs?
     Failure/Error: visit url_for(:controller => :apo, :action => :register)
     Capybara::InfiniteRedirectError:
       redirected more than 5 times, check for infinite redirects.
     # /Users/atz/.rvm/gems/ruby-2.2.0/gems/capybara-2.5.0/lib/capybara/rack_test/browser.rb:40:in `process_and_follow_redirects'
     # /Users/atz/.rvm/gems/ruby-2.2.0/gems/capybara-2.5.0/lib/capybara/rack_test/browser.rb:21:in `visit'
     # /Users/atz/.rvm/gems/ruby-2.2.0/gems/capybara-2.5.0/lib/capybara/rack_test/driver.rb:42:in `visit'
     # /Users/atz/.rvm/gems/ruby-2.2.0/gems/capybara-2.5.0/lib/capybara/session.rb:232:in `visit'
     # /Users/atz/.rvm/gems/ruby-2.2.0/gems/capybara-2.5.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/integration/apo_spec.rb:14:in `block (2 levels) in <top (required)>'

  8) mods_view item dialogs register should load the registration form
     # appears to pass even if blacklight JS isn't included in application.js or register.js, which you'd expect to break things.  skipping since it might be useless anyway.
     # ./spec/integration/item_displays_spec.rb:105

  9) User permitted_apos not implemented
     # Temporarily skipped with xit
     # ./spec/models/user_spec.rb:171

  10) User permitted_collections not implemented
     # Temporarily skipped with xit
     # ./spec/models/user_spec.rb:175
```

Several of the controller tests need to be moved to feature/integration tests.  Others reflect purely unimplemented features or unwritten tests.  I will take a stab at the controller --> feature tests.

**Comment by atz** [comment]
Down to 6 pending now.  Half or more are essentially because "this (test) is unimplemented".  So 2 or 3 actual expectations left to convert.

**Comment by mejackreed** [comment]
:clap: @atz

**Comment by atz** [comment]
Fixed a couple more but also added where I found gaps.  Pending now looks like:
```
  1) ApoController create should create an apo
     # Unimplemented test
     # ./spec/controllers/apo_controller_spec.rb:26

  2) DorController dor indexing all of the solr fields argo depends on should be in a solr doc generated by to_solr
     # unimplemented: required fields not fully/uniquely identified
     # ./spec/controllers/dor_controller_spec.rb:75

  3) mods_view item dialogs register should load the registration form
     # appears to pass even if blacklight JS isn't included in application.js or register.js, which you'd expect to break things.  skipping since it might be useless anyway.
     # ./spec/integration/item_displays_spec.rb:105

  4) ModsulatorJob generate_xml 
     # Not yet implemented
     # ./spec/jobs/modsulator_job_spec.rb:144

  5) User permitted_apos not implemented
     # Temporarily skipped with xit
     # ./spec/models/user_spec.rb:171

  6) User permitted_collections not implemented
     # Temporarily skipped with xit
     # ./spec/models/user_spec.rb:175

```
I'm mostly OK with that as is.

**Comment by drh-stanford** [comment]
ok closing
